# Keyword -> allergen name mapping
# Keys are lowercase; values are the canonical allergen name(s)

ALLERGEN_MAP: dict[str, list[str]] = {
    # Milk
    "milk": ["Milk"],
    "cream": ["Milk"],
    "butter": ["Milk"],
    "cheese": ["Milk"],
    "yoghurt": ["Milk"],
    "yogurt": ["Milk"],
    "ghee": ["Milk"],
    "whey": ["Milk"],
    "casein": ["Milk"],
    "lactose": ["Milk"],
    "curd": ["Milk"],
    "paneer": ["Milk"],
    "mascarpone": ["Milk"],
    "ricotta": ["Milk"],
    "mozzarella": ["Milk"],
    "parmesan": ["Milk"],
    "cheddar": ["Milk"],
    "brie": ["Milk"],
    "camembert": ["Milk"],
    "gouda": ["Milk"],
    "gruyere": ["Milk"],
    "emmental": ["Milk"],
    "stilton": ["Milk"],
    "halloumi": ["Milk"],
    "feta": ["Milk"],
    "cream cheese": ["Milk"],
    "double cream": ["Milk"],
    "single cream": ["Milk"],
    "clotted cream": ["Milk"],
    "sour cream": ["Milk"],
    "creme fraiche": ["Milk"],
    "buttermilk": ["Milk"],
    "condensed milk": ["Milk"],
    "evaporated milk": ["Milk"],
    "skimmed milk": ["Milk"],
    "whole milk": ["Milk"],
    "semi-skimmed milk": ["Milk"],
    # Gluten
    "flour": ["Gluten"],
    "wheat": ["Gluten"],
    "bread": ["Gluten"],
    "breadcrumbs": ["Gluten"],
    "pasta": ["Gluten"],
    "noodles": ["Gluten"],
    "linguine": ["Gluten"],
    "spaghetti": ["Gluten"],
    "penne": ["Gluten"],
    "fusilli": ["Gluten"],
    "tagliatelle": ["Gluten"],
    "lasagne": ["Gluten"],
    "ravioli": ["Gluten"],
    "gnocchi": ["Gluten"],
    "brioche": ["Gluten", "Milk", "Eggs"],
    "couscous": ["Gluten"],
    "bulgur": ["Gluten"],
    "semolina": ["Gluten"],
    "spelt": ["Gluten"],
    "rye": ["Gluten"],
    "barley": ["Gluten"],
    "oats": ["Gluten"],
    "oat": ["Gluten"],
    "soy sauce": ["Gluten", "Soybeans"],
    "tortilla": ["Gluten"],
    "wrap": ["Gluten"],
    "pitta": ["Gluten"],
    "pita": ["Gluten"],
    "croutons": ["Gluten"],
    "batter": ["Gluten"],
    "panko": ["Gluten"],
    "plain flour": ["Gluten"],
    "self-raising flour": ["Gluten"],
    "strong flour": ["Gluten"],
    "bread flour": ["Gluten"],
    "cake flour": ["Gluten"],
    "pastry": ["Gluten"],
    "puff pastry": ["Gluten"],
    "filo pastry": ["Gluten"],
    # Eggs
    "egg": ["Eggs"],
    "eggs": ["Eggs"],
    "mayonnaise": ["Eggs"],
    "mayo": ["Eggs"],
    "aioli": ["Eggs"],
    "meringue": ["Eggs"],
    "egg white": ["Eggs"],
    "egg yolk": ["Eggs"],
    "hollandaise": ["Eggs"],
    "custard": ["Eggs", "Milk"],
    "egg noodles": ["Eggs", "Gluten"],
    # Crustaceans
    "prawn": ["Crustaceans"],
    "prawns": ["Crustaceans"],
    "shrimp": ["Crustaceans"],
    "crab": ["Crustaceans"],
    "lobster": ["Crustaceans"],
    "crayfish": ["Crustaceans"],
    "langoustine": ["Crustaceans"],
    "scampi": ["Crustaceans"],
    # Peanuts
    "peanut": ["Peanuts"],
    "peanuts": ["Peanuts"],
    "peanut butter": ["Peanuts"],
    "groundnut": ["Peanuts"],
    "groundnuts": ["Peanuts"],
    "monkey nuts": ["Peanuts"],
    # Sesame
    "sesame": ["Sesame"],
    "sesame seeds": ["Sesame"],
    "sesame oil": ["Sesame"],
    "tahini": ["Sesame"],
    # Fish
    "fish": ["Fish"],
    "fish sauce": ["Fish"],
    "anchovies": ["Fish"],
    "anchovy": ["Fish"],
    "cod": ["Fish"],
    "salmon": ["Fish"],
    "tuna": ["Fish"],
    "mackerel": ["Fish"],
    "sardines": ["Fish"],
    "haddock": ["Fish"],
    "trout": ["Fish"],
    "sea bass": ["Fish"],
    "plaice": ["Fish"],
    "sole": ["Fish"],
    "halibut": ["Fish"],
    "swordfish": ["Fish"],
    "worcestershire sauce": ["Fish"],
    "nam pla": ["Fish"],
    # Mustard
    "mustard": ["Mustard"],
    "mustard seeds": ["Mustard"],
    "mustard powder": ["Mustard"],
    "wholegrain mustard": ["Mustard"],
    "dijon mustard": ["Mustard"],
    "english mustard": ["Mustard"],
    "curry paste": ["Mustard", "Celery"],
    # Celery
    "celery": ["Celery"],
    "celeriac": ["Celery"],
    "celery salt": ["Celery"],
    "celery seeds": ["Celery"],
    # Tree nuts
    "walnut": ["Tree Nuts"],
    "walnuts": ["Tree Nuts"],
    "almond": ["Tree Nuts"],
    "almonds": ["Tree Nuts"],
    "almond milk": ["Tree Nuts"],
    "almond flour": ["Tree Nuts"],
    "cashew": ["Tree Nuts"],
    "cashews": ["Tree Nuts"],
    "pistachio": ["Tree Nuts"],
    "pistachios": ["Tree Nuts"],
    "hazelnut": ["Tree Nuts"],
    "hazelnuts": ["Tree Nuts"],
    "pecan": ["Tree Nuts"],
    "pecans": ["Tree Nuts"],
    "macadamia": ["Tree Nuts"],
    "brazil nut": ["Tree Nuts"],
    "brazil nuts": ["Tree Nuts"],
    "pine nut": ["Tree Nuts"],
    "pine nuts": ["Tree Nuts"],
    "chestnut": ["Tree Nuts"],
    "chestnuts": ["Tree Nuts"],
    "praline": ["Tree Nuts"],
    "marzipan": ["Tree Nuts"],
    "frangipane": ["Tree Nuts"],
    # Soybeans
    "soy": ["Soybeans"],
    "soya": ["Soybeans"],
    "tofu": ["Soybeans"],
    "edamame": ["Soybeans"],
    "miso": ["Soybeans"],
    "tempeh": ["Soybeans"],
    "soybean": ["Soybeans"],
    "soybeans": ["Soybeans"],
    "soy milk": ["Soybeans"],
    "soya milk": ["Soybeans"],
    # Lupin
    "lupin": ["Lupin"],
    "lupin flour": ["Lupin"],
    "lupin seeds": ["Lupin"],
    "lupini beans": ["Lupin"],
    # Molluscs
    "squid": ["Molluscs"],
    "oyster": ["Molluscs"],
    "oysters": ["Molluscs"],
    "mussel": ["Molluscs"],
    "mussels": ["Molluscs"],
    "clam": ["Molluscs"],
    "clams": ["Molluscs"],
    "octopus": ["Molluscs"],
    "snails": ["Molluscs"],
    "escargot": ["Molluscs"],
    "calamari": ["Molluscs"],
    "oyster sauce": ["Molluscs"],
    # Sulphites
    "wine": ["Sulphites"],
    "red wine": ["Sulphites"],
    "white wine": ["Sulphites"],
    "beer": ["Sulphites"],
    "vinegar": ["Sulphites"],
    "balsamic vinegar": ["Sulphites"],
    "white wine vinegar": ["Sulphites"],
    "red wine vinegar": ["Sulphites"],
    "cider vinegar": ["Sulphites"],
    "dried fruit": ["Sulphites"],
    "dried apricots": ["Sulphites"],
    "sultanas": ["Sulphites"],
    "raisins": ["Sulphites"],
    "currants": ["Sulphites"],
}
